name = "claude-chat"
component_path = "/nix/store/aw9n3cmv5ydkh50jcpbw8mzhsx4qdjnz-claude-chat-0.1.0/lib/claude-chat.wasm"
short_description = "An HTTP server actor with REST API and WebSocket support for Claude chat"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "http-framework"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]

[[handlers]]
type = "supervisor"

[handlers.config]

