name = "claude-chat"
component_path = "/nix/store/zypnxpxbsyz0c1g9rkmcvdypdmkl1qfw-claude-chat-0.1.0/lib/claude-chat.wasm"
short_description = "An HTTP server actor with REST API and WebSocket support for Claude chat"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "http-framework"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]
